kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: devcamper-azurefile-storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: file.csi.azure.com # replace with "kubernetes.io/azure-file" if aks version is less than 1.21
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
  - noperm
  - nosharesock
  - nobrl
parameters:
  skuName: Premium_LRS
  location: uksouth
  secretNamespace: devcamper-namespace
  secretName: devcamper-db-secret
  shareName: devcamper-azure-file-share-dynamic
  storageAccount: devcamperstorageaccount
  resourceGroup: devcamper-rg
reclaimPolicy: Delete
volumeBindingMode: Immediate
